function [fitresult, gof] = createfit_2data(dataX, dataY)
%CREATEFIT(V_D_TEST,V_O_TEST)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : V_d_test
%      Y Output: V_o_test
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Jan-2021 14:30:46


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( dataX, dataY );

% Set up fittype and options.
ft = fittype( 'a*x+b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Robust = 'Bisquare';
opts.StartPoint = [0.497885993591747 0.916310033276035];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts )

% Plot fit with data.
%figure( 'Name', 'Regresion lineal' );
h = plot( fitresult, xData, yData );
legend( h, 'Scatter points', ['Pendiente = '  num2str(fitresult.a)], 'Location', 'NorthEast' );
% Label axes
xlabel('Label x')
ylabel('Label y')
grid on


